#!/bin/sh

RED="\e[31m"
YEL="\e[33m"
BLU="\e[94m"
ENDCOLOR="\e[0m"

if [ "$#" -ne 2 ]; then
    echo "Illegal number of parameters"
    exit
fi

LINE1="sudo iptables -v -I DOCKER-USER -i enp1s0 -s $1 -p tcp -m conntrack --ctorigdstport $2 --ctdir ORIGINAL -j ACCEPT"
LINE2="sudo iptables -v -I DOCKER-USER -i enp1s0 -p tcp -m conntrack --ctorigdstport $2 --ctdir ORIGINAL -j DROP"

COLOR1="sudo iptables -v -I DOCKER-USER -i enp1s0 -s ${BLU}$1${ENDCOLOR} -p tcp -m conntrack --ctorigdstport ${BLU}$2${ENDCOLOR} --ctdir ORIGINAL -j ACCEPT"
COLOR2="sudo iptables -v -I DOCKER-USER -i enp1s0 -p tcp -m conntrack --ctorigdstport ${BLU}$2${ENDCOLOR} --ctdir ORIGINAL -j DROP"


echo -e "${YEL}Rules to insert:${ENDCOLOR}"
echo -e "⚠️ $COLOR1"
echo -e "⚠️ $COLOR2"
read -p "Do you want to proceed? (yes/no) " yn

case $yn in
	yes | y) echo ok, we will proceed;
		break;;
	no | n) echo exiting...;
		exit;;
	* ) echo invalid response;
        exit;;
esac

$LINE2
$LINE1
